### ISSUE TITLE
AttributeError: 'Configuration' object has no attribute '_develop_range'

### ISSUE THREAD

**Issue by clohtd** [PrFalken/tessera-generate#1]
Have you ever run in to this?

server:/opt/tessera-generate #  ./tessera-generate.py --create --config-file=config.yaml --tessera-url="http://server:5000"

``` bash
Traceback (most recent call last):
  File "./tessera-generate.py", line 407, in <module>
    main()
  File "./tessera-generate.py", line 402, in main
    conf = Configuration(OPTIONS)
  File "./tessera-generate.py", line 87, in __init__
    self.nodes = self._expand_nodes()
  File "./tessera-generate.py", line 117, in _expand_nodes
    nodes[node] = self._develop_range(nodes[node])
AttributeError: 'Configuration' object has no attribute '_develop_range'
```

After hitting this with my own config.yaml, I tried copy/pasting your example config in and even that throws this error.

**Comment by clohtd** [comment]
piping a range to it on command line also throws the same error

**Comment by prfalken** [comment]
Oh you're right ! I forgot to move this method when I created the Configuration class. It is used when you specify nodes to expand in the configuration file.
I never really used the "nodes" section because I prefer to pass the nodes via stdin, so it went unnoticed.

fix is on its way. Thank you !

**Comment by clohtd** [comment]
Working.  Thanks very much.  This is a big help.
